language: cpp

sudo: false

cache: apt

notifications:
  email: false

_packages:
  - &default_packages
    - time # For build
  - &GCC-4_9
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-4.9-multilib
    before_install:
      - export CC="gcc-4.9"
      - export CXX="g++-4.9"
  - &GCC-5
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-5-multilib
    before_install:
      - export CC="gcc-5 -fuse-ld=gold"
      - export CXX="g++-5 -fuse-ld=gold"
  - &GCC-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-6-multilib
    before_install:
      - export CC="gcc-6 -fuse-ld=gold"
      - export CXX="g++-6 -fuse-ld=gold"
  - &Clang-3_5
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.5
        packages:
          - *default_packages
          - libstdc++-4.9-dev # The proper version of std library
          - clang-3.5
    before_install:
      - export CC="clang-3.5"
      - export CXX="clang++-3.5"
  - &Clang-3_6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - *default_packages
          - libstdc++-4.9-dev # The proper version of std library
          - clang-3.6
    before_install:
      - export CC="clang-3.6"
      - export CXX="clang++-3.6"
  - &Clang-3_7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
        packages:
          - *default_packages
          - libstdc++-4.9-dev # The proper version of std library
          - clang-3.7
    before_install:
      - export CC="clang-3.7"
      - export CXX="clang++-3.7"
  - &Clang-3_8
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
        packages:
          - *default_packages
          - libstdc++-4.9-dev # The proper version of std library
          - clang-3.8
    before_install:
      - export CC="clang-3.8"
      - export CXX="clang++-3.8"

matrix:
  fast_finish: true
  include:
    # GCC-4_9
    - compiler: gcc
      <<: *GCC-4_9
      env:
    - compiler: gcc
      <<: *GCC-4_9
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC-4_9
      env: DEBUG=2
    # GCC-5
    - compiler: gcc
      <<: *GCC-5
      env:
    - compiler: gcc
      <<: *GCC-5
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC-5
      env: DEBUG=2
    # GCC-6
    - compiler: gcc
      <<: *GCC-6
      env:
    - compiler: gcc
      <<: *GCC-6
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC-6
      env: DEBUG=2
    # Clang-3_5
    - compiler: clang
      <<: *Clang-3_5
      env:
    - compiler: clang
      <<: *Clang-3_5
      env: DEBUG=1
    - compiler: clang
      <<: *Clang-3_5
      env: DEBUG=2
    # Clang-3_6
    - compiler: clang
      <<: *Clang-3_6
      env:
    - compiler: clang
      <<: *Clang-3_6
      env: DEBUG=1
    - compiler: clang
      <<: *Clang-3_6
      env: DEBUG=2
    # Clang-3_7
    - compiler: clang
      <<: *Clang-3_7
      env:
    - compiler: clang
      <<: *Clang-3_7
      env: DEBUG=1
    # Clang-3_8
    - compiler: clang
      <<: *Clang-3_8
      env:
    - compiler: clang
      <<: *Clang-3_8
      env: DEBUG=1
    - compiler: clang
      <<: *Clang-3_8
      env: DEBUG=2
  # Because of a bug with Asan library
  allow_failures:
    - compiler: clang
      <<: *Clang-3_7
      env: DEBUG=2

before_script:
  - $CC -v
  - $CXX -v
  - export CC="$CC -Werror"
  - export CXX="$CXX -Werror"

script:
  - make -kj $(grep -c ^processor /proc/cpuinfo) DEBUG=$DEBUG
  - make -kj $(grep -c ^processor /proc/cpuinfo) DEBUG=$DEBUG test
